#!sh

###
# Basic SampShell definitions for _all_ interactive POSIX-complaint shells.
#
# This file isn't expected to be `.`'d directly, but rather by the top-level
# `interactive` script.
###

: "${SampShell_ROOTDIR:?}" # Sanity check, it should already have been done

# Ensure that the posix bin is included.
case ":$PATH:" in
	*:"$SampShell_ROOTDIR/posix/interactive-files/bin":*) ;;
	*) export PATH="$SampShell_ROOTDIR/posix/interactive-files/bin:$PATH" ;;
esac

# Setup the config files

set -- "$SampShell_ROOTDIR"/posix/interactive-files/*.sh

until [ "$#" -eq 0 ]; do
	. "$1"
	shift
done
