#!zsh
# Support `~[rr]`, which simply expands to the root of the repo

case $1 in
n)
	if [[ $2 != rr ]] return 1 # We only accept `~[rr]`

	# make reply a global array (if its not already)
	typeset -ga reply
	reply=( $(git rev-parse --show-toplevel 2>/dev/null) ) ;;

# To support expansions (eg in prompts), then uncomment the following
# d)
# 	local top
# 	top=$(git -C $2 rev-parse --show-toplevel 2>/dev/null) || return 1
# 	reply=( "rr($top:t)" $#top ) ;;

c)
	# complete names; adapted from documentation
	local expl
	_wanted dynamic-dirs expl 'dynamic directory' compadd -S\] rr ;;

*)
	# Nothing else is supported
	return 1
esac
