#!zsh

## Remove trailing newlines from lines that are "accepted" (ie when we hit enter)
# Strip out trailing whitespace. Note that we don't need to set `EXTENDED_GLOB` (or use the `(*)`
# parameter) as ZLE ensures it's always set.
if zstyle -T 'zle:accept-line' strip-whitespace; then
	# This isn't working currently
	# (( ! ${+NUMERIC} )) && zle SampShell-strip-whitespace -- 2 1
fi


# Call the builtin `accept-line` instead of this anything that may overwrite it (ie this fn).
zle .accept-line
