#!zsh

# If a prompt was previously pushed, then restore it.
if (( $+_SampShell_old_prompt )) then
	PS1=$_SampShell_old_prompt[1]
	RPS1=$_SampShell_old_prompt[2]
	unset -v _SampShell_old_prompt
else
	# If a count was given, then save the old prompt value. If no count's given, then assume
	# mark `PS1` and `RPS1` as local so their changes are only in this function.
	if (( $+NUMERIC )) then
		typeset -g +x _SampShell_old_prompt=($PS1 $RPS1)
	else
		local PS1 RPS1
	fi
	PS1='%% ' RPS1=
fi

# Reset the prompt so as to display the changes.
zle reset-prompt
