#!sh <-- just for syntax highlighting
# A sample interactive file

## ... other definitions to setup '$PATH' and stuff
[ -s "$HOME/.rvm/scripts/rvm" ] && . "$HOME/.rvm/scripts/rvm"
[ -s "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# Setup SampShell variables; SampShell will automatically export ones that need to be.
SampShell_TMPDIR=$HOME/tmp
SampShell_git_branch_prefix=swesterman

# Set the rootdir; this can be omitted in some shells (eg ZSH and Bash), as they
# can automatically infer it; see the top-level `env.sh` file for details.
SampShell_ROOTDIR=$HOME/.sampshell

# Load the config; the both.sh file will automatically ;pad the env and interactive as needed.
. "$SampShell_ROOTDIR/both.sh"

# Now do any setup that requires sampshell loaded.
