#!zsh

# typeset -Fg SECONDS
# setopt promptsubst
# PS4='\''+$SECONDS:%x:%I> '\'
(( ! $# )) && set -- -ic :

clean-shell \
	-n \
	-v SampShell_PROFILE= \
	-v SampShell_XTRACE=1 \
	-v SampShell_ROOTDIR \
	-v SampShell_CACHEDIR \
	-v SampShell_just_for_testing_should_disable_rvm=1 \
	-v PS4='+$(typeset -Fg SECONDS; echo "$SECONDS"):%x:%I> ' \
	-- \
	=zsh \
	--xtrace \
	--sourcetrace \
	--prompt-subst \
	${==@}
