#!zsh
read -sk chr # Read a character and put it into `$REPLY`

## If it doesn't exist in the string, beep and return.
if (( ! ${BUFFER[(I)$chr]} )) then
	zle beep
	return
fi

## The amount of times to delete, defaults to 1.
amount=${NUMERIC:-1}

## Stuff after the cursor
remainder=${BUFFER:$CURSOR}

## If it's positive, delete to the left, if it's negative, delete right.
if (( amount < 0 )) then
	for (( i = 0; i < -amount; i++ )); do
		remainder=${remainder#*$chr}
	done
else
	for (( i = 0; i < amount; i++ )); do
		BUFFER=${BUFFER%$chr*}
	done
fi

## Put the cursor back to the end of the buffer
CURSOR=$#BUFFER

## Append `remainder` to the end of thebuffer
BUFFER+=$post
